	TITLE	NULLGRAF
	PUBLIC	GRON,   GROFF,  CLS,    POINT,  MOVE,   DRAW,   HFILL,  VFILL
	PUBLIC	COLOR,  STYLE,  PATERN, INTENS, PALLET, BORDER, VIDEO,  HPAGE
	PUBLIC	NOCARD, PUSHXY, POPXY,  INXPOS, INYPOS, INPIX,  GETMAP, PUTMAP
	PUBLIC	ORMAP,  XORMAP, TRACK,  INKEY,  HASCII, HFONT,  HFONT8, OUTHLI
	PUBLIC	CIRB

DEFPRO	MACRO	ARG, PRLIST
	LOCAL	LAB
	IRP	X, <PRLIST>
X	LABEL	FAR
	ENDM
LAB	PROC	FAR
	RET	ARG
LAB	ENDP
	ENDM

CODE	SEGMENT	'CODE'
	ASSUME	CS:CODE

	DEFPRO	 , <GROFF, CLS, PUSHXY, POPXY>
	DEFPRO	4, <GRON, HFILL, VFILL, COLOR, STYLE, INTENS, PALLET, BORDER>
	DEFPRO	4, <VIDEO, NOCARD, INXPOS, INYPOS, PUTMAP, ORMAP, XORMAP, INKEY>
	DEFPRO	4, <HASCII>
	DEFPRO	8, <POINT, MOVE, DRAW, INPIX, TRACK, HFONT, HFONT8, OUTHLI>
	DEFPRO	12,<HPAGE, GETMAP>
	DEFPRO	16,<PATERN>
	DEFPRO	36,<CIRB>

CODE	ENDS
	END
